/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    BottomSticky: typeof import('./src/components/ui/BottomSticky.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Container: typeof import('./src/components/ui/Container.vue')['default']
    Divider: typeof import('./src/components/ui/Divider.vue')['default']
    EmptyState: typeof import('./src/components/ui/EmptyState.vue')['default']
    Flex: typeof import('./src/components/ui/Flex.vue')['default']
    OutsetBox: typeof import('./src/components/ui/OutsetBox.vue')['default']
    PageHeader: typeof import('./src/components/ui/PageHeader.vue')['default']
    ResultView: typeof import('./src/components/ui/ResultView.vue')['default']
    Section: typeof import('./src/components/ui/Section.vue')['default']
    TextButton: typeof import('./src/components/ui/TextButton.vue')['default']
  }
}
