/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    Badge: typeof import('./src/components/ui/Badge.vue')['default']
    BottomSticky: typeof import('./src/components/ui/BottomSticky.vue')['default']
    Box: typeof import('./src/components/ui/Box.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Container: typeof import('./src/components/ui/Container.vue')['default']
    copy: typeof import('./src/components/ui/TextInput copy.vue')['default']
    Divider: typeof import('./src/components/ui/Divider.vue')['default']
    Flex: typeof import('./src/components/ui/Flex.vue')['default']
    FloatingTextInput: typeof import('./src/components/ui/FloatingTextInput.vue')['default']
    FormGroup: typeof import('./src/components/ui/FormGroup.vue')['default']
    FormLabel: typeof import('./src/components/ui/FormLabel.vue')['default']
    Lottie: typeof import('./src/components/ui/Lottie.vue')['default']
    OutsetBox: typeof import('./src/components/ui/OutsetBox.vue')['default']
    PageHeader: typeof import('./src/components/ui/PageHeader.vue')['default']
    ResultView: typeof import('./src/components/ui/ResultView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./src/components/ui/Section.vue')['default']
    Select: typeof import('./src/components/ui/Select.vue')['default']
    Tag: typeof import('./src/components/ui/Tag.vue')['default']
    Textarea: typeof import('./src/components/ui/Textarea.vue')['default']
    TextArea: typeof import('./src/components/ui/TextArea.vue')['default']
    TextButton: typeof import('./src/components/ui/TextButton.vue')['default']
    TextInput: typeof import('./src/components/ui/TextInput.vue')['default']
    TextInputFloating: typeof import('./src/components/ui/TextInputFloating.vue')['default']
    TextInputMotion: typeof import('./src/components/ui/TextInputMotion.vue')['default']
    Typo: typeof import('./src/components/ui/Typo.vue')['default']
  }
}
